EDITOR-#22 [Backend] Article Resolvers Completed
NTUEE-Web-Programming-Final-Project/final-project pull request #27
Opened 2023-10-14 03:19 UTC by Jackbear8868

model Article
Query.tsx
- [x]  AllArticle

Mutation.tsx
- [x] CreateArticle
- [x]  DeleteArticle
- [x]  UpdateArticle

Subscription.tsx
- [x]  ArticleCreated
- [x]  ArticleDeleted
- [x]  ArticleUpdated

2023-10-14 03:19 UTC, Jackbear8868 commented
model ArticleComment
Query.tsx
- [x]  AllArticleComment
Mutation.tsx
- [x]  CreateArticleComment
- [x]  DeleteArticleComment
- [x]  UpdateArticleComment
Subscription.tsx
- [x]  ArticleCommentCreated
- [x]  ArticleCommentDeleted
- [x]  ArticleCommentUpdated

2023-10-14 09:05 UTC, ChenBingWei1201 requested changes
please fix some errors

2023-10-15 07:40 UTC, ChenBingWei1201 reviewed
- `zap`, `isMe`, and `bombFish` should keep their value when being updated.
- I forgot to add `zap` into `ArticleComment` and `QuestionComment` in `schema.prisma`
Would you please help me add it to them? Thanks a lot.

2023-10-15 07:44 UTC, ChenBingWei1201 requested changes
- `zap`, `isMe`, and `bombFish` should keep their value when being updated.
- I forgot to add `zap` into `ArticleComment` and `QuestionComment` in `schema.prisma`
Would you please help me add it to them? Thanks a lot.

2023-10-15 07:44 UTC, ChenBingWei1201 commented on backend/src/resolvers/Mutation.ts
> +        zap: 0,
`UpdateArticle` should keep the original zap numbers instead of resetting them.

2023-12-06 11:40 UTC, merged